# Generated by Django 3.0.5 on 2020-04-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WineItem',
            fields=[
                ('item_key', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('bottle_image_url', models.URLField(blank=True, null=True)),
                ('label_type', models.CharField(blank=True, choices=[('TR', 'Traditional'), ('WH', 'Whimsical'), ('CO', 'Colorful'), ('MO', 'Modern'), ('MI', 'Minimalist')], max_length=2, null=True)),
                ('closure_type', models.CharField(blank=True, choices=[('CO', 'Cork'), ('SC', 'Screwtop')], max_length=2, null=True)),
                ('country', models.TextField()),
                ('region', models.TextField()),
                ('origin', models.TextField()),
                ('wine_type', models.CharField(choices=[('R', 'Red'), ('W', 'White'), ('S', 'Sparkling'), ('Ro', 'Rose')], max_length=2)),
                ('varietal', models.TextField()),
                ('vintage', models.IntegerField()),
                ('point_score', models.IntegerField(blank=True, null=True)),
                ('story', models.TextField(blank=True, null=True)),
                ('user_rating', models.FloatField(blank=True, null=True)),
                ('sale_price', models.FloatField(blank=True, null=True)),
                ('original_url', models.URLField(blank=True, null=True)),
                ('tasting_notes', models.TextField(blank=True, null=True)),
                ('winc_product_id', models.TextField(blank=True, null=True)),
                ('winc_product_code', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
