# Generated by Django 3.0.5 on 2020-04-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wineitem',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wineitem',
            name='origin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wineitem',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wineitem',
            name='varietal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wineitem',
            name='vintage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
