# Generated by Django 3.0.5 on 2020-05-01 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20200430_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('slug', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=120)),
                ('survey_question_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.SurveyQuestion')),
                ('survey_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyResponse')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyABTestInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_A', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='survey.WineItem')),
                ('item_B', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='survey.WineItem')),
                ('loser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='survey.WineItem')),
                ('survey_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.SurveyResponse')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='survey.WineItem')),
            ],
        ),
    ]
