# Generated by Django 3.0.5 on 2020-05-02 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_surveyabtestinstance_surveyquestion_surveyquestionresponse_surveyresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyquestionresponse',
            old_name='survey_question_item',
            new_name='survey_question',
        ),
    ]
