# Generated by Django 3.0.5 on 2020-05-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20200502_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyabtestinstance',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
