# Generated by Django 3.0.5 on 2020-05-06 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_surveyabtestinstance_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyabtestinstance',
            name='item_A',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.WineItem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyabtestinstance',
            name='item_B',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.WineItem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyabtestinstance',
            name='loser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.WineItem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyabtestinstance',
            name='survey_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyResponse'),
        ),
        migrations.AlterField(
            model_name='surveyabtestinstance',
            name='winner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.WineItem'),
            preserve_default=False,
        ),
    ]
