# Generated by Django 3.0.5 on 2020-05-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20200506_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='wineitem',
            name='wine_product_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
